/**
 * API: Incident Reports
 * POST /api/guide/incidents - Create incident report
 */

import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';

import { withErrorHandler } from '@/lib/api/error-handler';
import { getBranchContext, withBranchFilter } from '@/lib/branch/branch-injection';
import { sendTextMessage } from '@/lib/integrations/whatsapp';
import { createClient } from '@/lib/supabase/server';
import { logger } from '@/lib/utils/logger';

const incidentSchema = z.object({
  incidentType: z.enum(['accident', 'injury', 'equipment_damage', 'weather_issue', 'complaint', 'other']),
  chronology: z.string().min(10, 'Kronologi minimal 10 karakter'),
  witnesses: z.string().optional(),
  photoUrls: z.array(z.string().url()).optional(),
  tripId: z.string().uuid().optional(),
  signature: z.object({
    method: z.enum(['draw', 'upload', 'typed']),
    data: z.string(),
  }).optional(),
});

export const POST = withErrorHandler(async (request: NextRequest) => {
  const supabase = await createClient();
  const payload = incidentSchema.parse(await request.json());

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { incidentType, chronology, witnesses, photoUrls, tripId, signature } = payload;

  const branchContext = await getBranchContext(user.id);
  const client = supabase as unknown as any;

  // Insert incident report (report_number will be auto-generated by trigger)
  const { data: report, error: reportError } = await withBranchFilter(
    client.from('incident_reports'),
    branchContext,
  )
    .insert({
      guide_id: user.id,
      trip_id: tripId || null,
      branch_id: branchContext.branchId,
      incident_type: incidentType,
      chronology,
      witnesses: witnesses || null,
      photo_urls: photoUrls || [],
      signature_data: signature?.data || null,
      signature_method: signature?.method || null,
      signature_timestamp: signature ? new Date().toISOString() : null,
      status: 'reported',
      notified_insurance: false,
      notified_admin: false,
      created_at: new Date().toISOString(),
    })
    .select('id, report_number')
    .single();

  if (reportError) {
    logger.error('Incident report creation failed', reportError, {
      guideId: user.id,
      tripId,
      incidentType,
    });
    return NextResponse.json({ error: 'Failed to create incident report' }, { status: 500 });
  }

  logger.info('Incident report created', {
    reportId: report.id,
    reportNumber: report.report_number,
    guideId: user.id,
    tripId,
    incidentType,
  });

  // Auto-notify insurance & admin (async, don't wait)
  try {
    await notifyIncidentReport(report.id, report.report_number, incidentType, tripId || null, branchContext.branchId || null);
  } catch (notifyError) {
    logger.error('Failed to send notifications', notifyError, { reportId: report.id });
    // Don't fail the request if notification fails
  }

  return NextResponse.json({
    success: true,
    reportId: report.id,
    reportNumber: report.report_number,
  });
});

/**
 * Notify insurance & admin about new incident report
 */
async function notifyIncidentReport(
  reportId: string,
  reportNumber: string | null,
  incidentType: string,
  tripId: string | null,
  branchId: string | null
) {
  const { createClient } = await import('@/lib/supabase/server');
  const supabase = await createClient();

  try {
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      logger.warn('Cannot notify incident report: user not found', { reportId });
      return;
    }

    // Get guide info
    const { data: guideData } = await (supabase as unknown as any)
      .from('users')
      .select('full_name, phone')
      .eq('id', user.id)
      .single();

    // Get trip info if available
    let tripCode = null;
    if (tripId) {
      const { data: tripData } = await (supabase as unknown as any)
        .from('trips')
        .select('trip_code')
        .eq('id', tripId)
        .maybeSingle();
      tripCode = tripData?.trip_code || null;
    }

    // Prepare notification message
    const incidentTypeLabels: Record<string, string> = {
      accident: 'Kecelakaan',
      injury: 'Cedera',
      equipment_damage: 'Kerusakan Peralatan',
      weather_issue: 'Masalah Cuaca',
      complaint: 'Keluhan',
      other: 'Lainnya',
    };

    const message = [
      '🚨 *LAPORAN INSIDEN BARU* 🚨',
      '',
      `No. Laporan: ${reportNumber || reportId.slice(0, 8)}`,
      `Jenis: ${incidentTypeLabels[incidentType] || incidentType}`,
      `Guide: ${guideData?.full_name || 'Unknown'}`,
      tripCode ? `Trip: ${tripCode}` : null,
      '',
      'Mohon segera ditindaklanjuti dari dashboard Admin.',
      `Detail: ${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/admin/incidents/${reportId}`,
    ]
      .filter(Boolean)
      .join('\n');

    // Notify admin via WhatsApp
    const opsPhone = process.env.WHATSAPP_OPS_PHONE;
    if (opsPhone) {
      try {
        await sendTextMessage(opsPhone, message);
        logger.info('Incident report notification sent to admin', { reportId, opsPhone });
      } catch (waError) {
        logger.error('Failed to send WhatsApp notification', waError, { reportId });
      }
    }

    // Notify insurance (if configured)
    const insurancePhone = process.env.WHATSAPP_INSURANCE_PHONE;
    if (insurancePhone && (incidentType === 'accident' || incidentType === 'injury')) {
      try {
        await sendTextMessage(insurancePhone, message);
        logger.info('Incident report notification sent to insurance', { reportId, insurancePhone });
      } catch (waError) {
        logger.error('Failed to send WhatsApp notification to insurance', waError, { reportId });
      }
    }

    // Update notification status in database
    await (supabase as unknown as any)
      .from('incident_reports')
      .update({
        notified_admin: !!opsPhone,
        notified_insurance: !!insurancePhone && (incidentType === 'accident' || incidentType === 'injury'),
        notification_sent_at: new Date().toISOString(),
      })
      .eq('id', reportId);

    logger.info('Incident report notification completed', {
      reportId,
      reportNumber,
      incidentType,
      tripId,
    });
  } catch (error) {
    logger.error('Failed to send incident report notifications', error, { reportId });
    throw error;
  }
}
