-- Migration: seo-pages.sql
-- Description: SEO Pages for Programmatic SEO (PRD 5.2.C & 5.3.A)
-- Created: 2026-01-02

BEGIN;

-- ============================================
-- SEO PAGES TABLE
-- Stores AI-generated SEO content for landing pages
-- ============================================
CREATE TABLE IF NOT EXISTS seo_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  package_id UUID NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  origin_city VARCHAR(100) NOT NULL,
  slug VARCHAR(200) NOT NULL,
  
  -- SEO Content (generated by AI Content Spinner)
  title VARCHAR(200) NOT NULL,
  description TEXT,
  meta_description VARCHAR(200),
  h1 VARCHAR(200),
  h2 TEXT[], -- Array of subheadings
  content TEXT,
  keywords TEXT[],
  
  -- Package Info (denormalized for performance)
  package_name VARCHAR(300),
  package_destination VARCHAR(200),
  
  -- Status
  is_published BOOLEAN DEFAULT true,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Audit
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(package_id, origin_city)
);

-- ============================================
-- INDEXES
-- ============================================
CREATE INDEX IF NOT EXISTS idx_seo_pages_slug ON seo_pages(slug);
CREATE INDEX IF NOT EXISTS idx_seo_pages_origin_city ON seo_pages(origin_city);
CREATE INDEX IF NOT EXISTS idx_seo_pages_package_id ON seo_pages(package_id);
CREATE INDEX IF NOT EXISTS idx_seo_pages_is_published ON seo_pages(is_published) WHERE is_published = true;

-- ============================================
-- TRIGGERS
-- ============================================
CREATE TRIGGER update_seo_pages_updated_at
  BEFORE UPDATE ON seo_pages
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- RLS POLICIES
-- ============================================
ALTER TABLE seo_pages ENABLE ROW LEVEL SECURITY;

-- Public read access for published pages
CREATE POLICY "Public can read published SEO pages"
  ON seo_pages
  FOR SELECT
  USING (is_published = true);

-- Admin full access
CREATE POLICY "Admins can manage SEO pages"
  ON seo_pages
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE users.id = auth.uid()
      AND users.role IN ('super_admin', 'ops_admin', 'marketing')
    )
  );

COMMIT;

